[package]
name = "gmt-ns-im"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
chrono = "=0.4.34"
gmt-fem = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "5.1.1" }
gmt_dos-actors = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "11.2.0" }
gmt_dos-actors-clients_interface = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "1.3.2" }
gmt_dos-clients = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "5.0.0" }
gmt_dos-clients_fem = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "5.1.0", features = ["cuda"] }
gmt_dos-clients_io = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "4.2.2" }
gmt_dos-clients_m1-ctrl = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "5.0.0" }
gmt_dos-clients_m2-ctrl = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "4.0.0" }
gmt_dos-clients_mount = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "4.1.0" }
gmt_dos-systems_m1 = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "0.1.0" }
gmt_dos-systems_m2 = { git = "https://github.com/rconan/dos-actors.git", branch = "fsms", version = "0.1.0" }
tokio = { version = "1.43.0", features = ["full"] }

# [patch."https://github.com/rconan/dos-actors.git"]
# gmt-fem = { path = "/home/rconan/projects/dos-actors/clients/fem/model"}
# gmt_dos-actors= { path = "/home/rconan/projects/dos-actors/actors"}
# gmt_dos-clients = { path = "/home/rconan/projects/dos-actors/clients/core"}
# gmt_dos-clients_io = { path = "/home/rconan/projects/dos-actors/clients/io"}
# gmt_dos-clients_fem = { path = "/home/rconan/projects/dos-actors/clients/fem"}
# gmt_dos-clients_mount = { path = "/home/rconan/projects/dos-actors/clients/mount"}
# gmt_dos-clients_m1-ctrl = { path = "/home/rconan/projects/dos-actors/clients/m1-ctrl"}
# gmt_dos-systems_m1 = { path = "/home/rconan/projects/dos-actors/systems/m1"}
# gmt_dos-actors-clients_interface = { path = "/home/rconan/projects/dos-actors/interface"}
