[package]
name = "calibrations"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
faer = "0.21.7"
gmt_dos-clients_crseo.workspace = true
gmt_dos-systems_agws.workspace = true
matio-rs.workspace = true
serde-pickle = "1.2.0"
skyangle = "0.3.1"
