[package]
name = "scopes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_lom.workspace = true
gmt_dos-clients_scope-client.workspace = true
interface.workspace = true
tokio.workspace = true
